name: 'Replace Strings'
description: 'Greet someone and record the time'
inputs:
  file: # id of input
    description: 'File to replace'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
